//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestmove.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bd_gestmoveEntities : DbContext
    {
        public bd_gestmoveEntities()
            : base("name=bd_gestmoveEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_abastecimento> tb_abastecimento { get; set; }
        public virtual DbSet<tb_empresa> tb_empresa { get; set; }
        public virtual DbSet<tb_locacao> tb_locacao { get; set; }
        public virtual DbSet<tb_login> tb_login { get; set; }
        public virtual DbSet<tb_manutencao> tb_manutencao { get; set; }
        public virtual DbSet<tb_pessoa> tb_pessoa { get; set; }
        public virtual DbSet<tb_posto> tb_posto { get; set; }
        public virtual DbSet<tb_veiculo> tb_veiculo { get; set; }
        public virtual DbSet<tb_viagem> tb_viagem { get; set; }
    }
}
