//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestmove.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_abastecimento
    {
        public int cod_abastecimento { get; set; }
        public int cod_veiculo { get; set; }
        public int cod_posto { get; set; }
        public System.DateTime data { get; set; }
        public int litros { get; set; }
        public decimal valor { get; set; }
    }
}
