//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestmove.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_login
    {
        public int ID { get; set; }
        public string usuario { get; set; }
        public string senha { get; set; }
        public Nullable<int> nv_user { get; set; }
    }
}
