//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestmove.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_manutencao
    {
        public int cod_manutencao { get; set; }
        public Nullable<int> cod_veiculo { get; set; }
        public Nullable<int> cod_oficina { get; set; }
        public string tipo { get; set; }
        public string motivo { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public Nullable<double> valor { get; set; }
    
        public virtual tb_pessoa tb_pessoa { get; set; }
        public virtual tb_veiculo tb_veiculo { get; set; }
    }
}
