//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestmove.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ocorrencia
    {
        public int cod_ocorrencia { get; set; }
        public int cod_viagem { get; set; }
        public int cod_motorista { get; set; }
        public int cod_veiculo { get; set; }
        public string motivo { get; set; }
        public Nullable<int> pontos { get; set; }
        public decimal valor { get; set; }
        public string obs_motorista { get; set; }
    
        public virtual tb_pessoa tb_pessoa { get; set; }
        public virtual tb_veiculo tb_veiculo { get; set; }
        public virtual tb_viagem tb_viagem { get; set; }
    }
}
