//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestmove.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_pessoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_pessoa()
        {
            this.tb_locacao = new HashSet<tb_locacao>();
            this.tb_manutencao = new HashSet<tb_manutencao>();
            this.tb_ocorrencia = new HashSet<tb_ocorrencia>();
            this.tb_viagem = new HashSet<tb_viagem>();
            this.tb_viagem1 = new HashSet<tb_viagem>();
        }
    
        public int ID_pessoa { get; set; }
        public int tipo { get; set; }
        public string nome_abreviado { get; set; }
        public string razao_social { get; set; }
        public string f_j { get; set; }
        public string rg_cnpj { get; set; }
        public string cpf_ie { get; set; }
        public string logradouro { get; set; }
        public int numero { get; set; }
        public string compl { get; set; }
        public string cep { get; set; }
        public string bairro { get; set; }
        public string municipio { get; set; }
        public string uf { get; set; }
        public string regiao { get; set; }
        public string telefone { get; set; }
        public string celular { get; set; }
        public string email { get; set; }
        public string tipo_carteira { get; set; }
        public string cnh { get; set; }
        public Nullable<int> pontos_carteira { get; set; }
        public System.DateTime data_contratacao { get; set; }
        public string tipo_fornec_msa { get; set; }
        public string tipo_msa1 { get; set; }
        public string tipo_msa2 { get; set; }
        public string tipo_msa3 { get; set; }
        public string observacao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_locacao> tb_locacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_manutencao> tb_manutencao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ocorrencia> tb_ocorrencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_viagem> tb_viagem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_viagem> tb_viagem1 { get; set; }
    }
}
