//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestmove.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_posto
    {
        public int ID { get; set; }
        public string nome_abreviado { get; set; }
        public string razao_social { get; set; }
        public string logradouro { get; set; }
        public int numero { get; set; }
        public string compl { get; set; }
        public string cep { get; set; }
        public string bairro { get; set; }
        public string municipio { get; set; }
        public string uf { get; set; }
        public string regiao { get; set; }
        public string observacao { get; set; }
    }
}
