//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestmove.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_seguro
    {
        public int id_seguro { get; set; }
        public Nullable<int> cnh { get; set; }
        public Nullable<int> rg { get; set; }
        public Nullable<int> crv { get; set; }
        public Nullable<int> crvl { get; set; }
        public Nullable<int> cod_veiculo { get; set; }
    
        public virtual tb_veiculo tb_veiculo { get; set; }
    }
}
