//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestmove.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_veiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_veiculo()
        {
            this.tb_locacao = new HashSet<tb_locacao>();
            this.tb_manutencao = new HashSet<tb_manutencao>();
            this.tb_viagem = new HashSet<tb_viagem>();
        }
    
        public int cod_veiculo { get; set; }
        public string proprio_alugado { get; set; }
        public Nullable<int> cod_fornecedor { get; set; }
        public string placa { get; set; }
        public string uf { get; set; }
        public string chassi { get; set; }
        public int tipo_chassi { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public string cor { get; set; }
        public Nullable<int> km { get; set; }
        public string combustivel { get; set; }
        public string observacao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_locacao> tb_locacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_manutencao> tb_manutencao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_viagem> tb_viagem { get; set; }
    }
}
